name: Run docker-compose up -d on develop branch

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: develop
    - name: Run docker-compose up -d
      uses: alex-ac/github-action-ssh-docker-compose@v1.0.0
